### ISSUE TITLE
CI testing failing

### ISSUE THREAD

**Issue by korseby** [phnmnl/ipo_docker#2]
The test in Jenkins is failing with:

```
Error in plot.new() : 
  could not open file 'contTest/rsmDirectory/rsm_1.jpg'
Calls: optimizeXcmsSet ... image -> image.default -> plot -> plot.default -> plot.new
In addition: Warning message:
In dir.create(subdir) :
  cannot create dir 'contTest/rsmDirectory', reason 'No such file or directory'
Execution halted
JPG graph rsm_1.jpg not found, failing test
release "ipo-gt5jz" deleted
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

I guess, the scripts wants to write to a directory which is not there or do not have permissions inside the container to write. @pcm32 can you have a look? 

@gabrielctn ist currently working on the container, too.

Best wishes

**Comment by gabrielctn** [comment]
Now a new issue:
```
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: cannot open the connection
Calls: optimizeXcmsSet ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
JPG graph rsm_1.jpg not found, failing test
release "ipo-gt4j5" deleted
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
Seems to come from a "hardware" problem, parallelization problem maybe ?

**Comment by gabrielctn** [comment]
But it is not a problem since I am currently working on galaxy R and XML wrappers that will come soon replace the runIPO.r script.

**Comment by sneumann** [comment]
Good to see that http://phenomenal-h2020.eu/jenkins/job/container-ipo/ is passing again. Yours, Steffen

**Comment by gabrielctn** [comment]
Not for long I fear ;)
